name: practical basics

on: 
 push:
  branches:
   - main 
 workflow_dispatch:


jobs:
  lesson1:
    runs-on: ubuntu-latest
    env:
      SITE_NAME : MY-DEMO-SITE
      OWNER : AMIRAM

    steps:
      - name : step0 - chekout repository
        uses: actions/checkout@v4
      - name : step1 - print site name
        run: echo "site name is $SITE_NAME"
      - name : step2 - print owner name
        run: echo "owner name is $OWNER"
      - name : step3 - show current folder
        run : pwd
      - name : step4 - list files in current folder
        run : ls -la 